"""Fix geocodificación: eliminar FK mentions.country_code + ampliar tabla countries

Revision ID: 016
Revises: 015
Create Date: 2026-04-10
"""
from alembic import op
import sqlalchemy as sa

revision = "016"
down_revision = "015"
branch_labels = None
depends_on = None


def upgrade():
    # 1. Eliminar FK constraint de mentions.country_code
    #    El nombre lo genera PostgreSQL automáticamente: {tabla}_{columna}_fkey
    op.drop_constraint("mentions_country_code_fkey", "mentions", type_="foreignkey")

    # 2. Insertar países del mundo faltantes (los 12 originales ya existen)
    op.execute("""
        INSERT INTO countries (code, name) VALUES
        ('BR', 'Brasil'),
        ('CA', 'Canadá'),
        ('GB', 'Reino Unido'),
        ('DE', 'Alemania'),
        ('FR', 'Francia'),
        ('IT', 'Italia'),
        ('PT', 'Portugal'),
        ('AU', 'Australia'),
        ('NZ', 'Nueva Zelanda'),
        ('JP', 'Japón'),
        ('CN', 'China'),
        ('IN', 'India'),
        ('ZA', 'Sudáfrica'),
        ('NG', 'Nigeria'),
        ('EG', 'Egipto'),
        ('MA', 'Marruecos'),
        ('KE', 'Kenia'),
        ('GH', 'Ghana'),
        ('TR', 'Turquía'),
        ('SA', 'Arabia Saudita'),
        ('AE', 'Emiratos Árabes'),
        ('IL', 'Israel'),
        ('RU', 'Rusia'),
        ('UA', 'Ucrania'),
        ('PL', 'Polonia'),
        ('NL', 'Países Bajos'),
        ('SE', 'Suecia'),
        ('NO', 'Noruega'),
        ('DK', 'Dinamarca'),
        ('FI', 'Finlandia'),
        ('BE', 'Bélgica'),
        ('CH', 'Suiza'),
        ('AT', 'Austria'),
        ('CZ', 'República Checa'),
        ('HU', 'Hungría'),
        ('RO', 'Rumania'),
        ('GR', 'Grecia'),
        ('HK', 'Hong Kong'),
        ('SG', 'Singapur'),
        ('PH', 'Filipinas'),
        ('ID', 'Indonesia'),
        ('MY', 'Malasia'),
        ('TH', 'Tailandia'),
        ('KR', 'Corea del Sur'),
        ('PK', 'Pakistán'),
        ('BD', 'Bangladesh'),
        ('TZ', 'Tanzania'),
        ('GT', 'Guatemala'),
        ('HN', 'Honduras'),
        ('SV', 'El Salvador'),
        ('NI', 'Nicaragua'),
        ('CR', 'Costa Rica'),
        ('PA', 'Panamá'),
        ('DO', 'República Dominicana'),
        ('PR', 'Puerto Rico'),
        ('CU', 'Cuba'),
        ('JM', 'Jamaica'),
        ('TT', 'Trinidad y Tobago'),
        ('HT', 'Haití'),
        ('GY', 'Guyana'),
        ('SR', 'Surinam'),
        ('TW', 'Taiwán'),
        ('IR', 'Irán'),
        ('IQ', 'Irak'),
        ('AF', 'Afganistán'),
        ('PY', 'Paraguay'),
        ('ET', 'Etiopía'),
        ('TN', 'Túnez'),
        ('DZ', 'Argelia'),
        ('LY', 'Libia'),
        ('SD', 'Sudán'),
        ('SO', 'Somalia'),
        ('SN', 'Senegal'),
        ('CI', 'Costa de Marfil'),
        ('CM', 'Camerún'),
        ('UG', 'Uganda'),
        ('ZM', 'Zambia'),
        ('ZW', 'Zimbabue'),
        ('MZ', 'Mozambique'),
        ('AO', 'Angola'),
        ('MW', 'Malaui'),
        ('RW', 'Ruanda'),
        ('BF', 'Burkina Faso'),
        ('ML', 'Mali'),
        ('NE', 'Níger'),
        ('TD', 'Chad'),
        ('CD', 'R. D. Congo'),
        ('CG', 'Congo'),
        ('GA', 'Gabón'),
        ('GQ', 'Guinea Ecuatorial'),
        ('ST', 'Santo Tomé y Príncipe'),
        ('CV', 'Cabo Verde'),
        ('MR', 'Mauritania'),
        ('GM', 'Gambia'),
        ('GW', 'Guinea-Bisáu'),
        ('GN', 'Guinea'),
        ('SL', 'Sierra Leona'),
        ('LR', 'Liberia'),
        ('ER', 'Eritrea'),
        ('DJ', 'Yibuti'),
        ('SC', 'Seychelles'),
        ('MU', 'Mauricio'),
        ('MG', 'Madagascar'),
        ('KM', 'Comoras'),
        ('BJ', 'Benín'),
        ('TG', 'Togo'),
        ('BW', 'Botsuana'),
        ('NA', 'Namibia'),
        ('SZ', 'Esuatini'),
        ('LS', 'Lesoto'),
        ('SK', 'Eslovaquia'),
        ('SI', 'Eslovenia'),
        ('HR', 'Croacia'),
        ('BA', 'Bosnia y Herzegovina'),
        ('RS', 'Serbia'),
        ('ME', 'Montenegro'),
        ('MK', 'Macedonia del Norte'),
        ('AL', 'Albania'),
        ('BG', 'Bulgaria'),
        ('EE', 'Estonia'),
        ('LV', 'Letonia'),
        ('LT', 'Lituania'),
        ('BY', 'Bielorrusia'),
        ('MD', 'Moldavia'),
        ('GE', 'Georgia'),
        ('AM', 'Armenia'),
        ('AZ', 'Azerbaiyán'),
        ('KZ', 'Kazajistán'),
        ('UZ', 'Uzbekistán'),
        ('TM', 'Turkmenistán'),
        ('KG', 'Kirguistán'),
        ('TJ', 'Tayikistán'),
        ('MN', 'Mongolia'),
        ('NP', 'Nepal'),
        ('LK', 'Sri Lanka'),
        ('MM', 'Myanmar'),
        ('KH', 'Camboya'),
        ('LA', 'Laos'),
        ('VN', 'Vietnam'),
        ('BN', 'Brunéi'),
        ('TL', 'Timor Oriental'),
        ('PG', 'Papúa Nueva Guinea'),
        ('FJ', 'Fiyi'),
        ('WS', 'Samoa'),
        ('TO', 'Tonga'),
        ('VU', 'Vanuatu'),
        ('SB', 'Islas Salomón'),
        ('KI', 'Kiribati'),
        ('FM', 'Micronesia'),
        ('MH', 'Islas Marshall'),
        ('PW', 'Palaos'),
        ('NR', 'Nauru'),
        ('TV', 'Tuvalu'),
        ('CY', 'Chipre'),
        ('MT', 'Malta'),
        ('IS', 'Islandia'),
        ('LU', 'Luxemburgo'),
        ('LI', 'Liechtenstein'),
        ('MC', 'Mónaco'),
        ('SM', 'San Marino'),
        ('VA', 'Ciudad del Vaticano'),
        ('AD', 'Andorra'),
        ('IE', 'Irlanda'),
        ('PT', 'Portugal'),
        ('JO', 'Jordania'),
        ('LB', 'Líbano'),
        ('SY', 'Siria'),
        ('YE', 'Yemen'),
        ('KW', 'Kuwait'),
        ('BH', 'Baréin'),
        ('QA', 'Catar'),
        ('OM', 'Omán'),
        ('MV', 'Maldivas'),
        ('BT', 'Bután'),
        ('KP', 'Corea del Norte'),
        ('PA', 'Panamá'),
        ('EC', 'Ecuador'),
        ('BB', 'Barbados'),
        ('LC', 'Santa Lucía'),
        ('VC', 'San Vicente y las Granadinas'),
        ('GD', 'Granada'),
        ('DM', 'Dominica'),
        ('KN', 'San Cristóbal y Nieves'),
        ('AG', 'Antigua y Barbuda'),
        ('BS', 'Bahamas'),
        ('TC', 'Islas Turcas y Caicos'),
        ('KY', 'Islas Caimán'),
        ('BZ', 'Belice')
        ON CONFLICT (code) DO NOTHING
    """)


def downgrade():
    # Restaurar FK en mentions.country_code
    op.create_foreign_key(
        "mentions_country_code_fkey",
        "mentions",
        "countries",
        ["country_code"],
        ["code"],
    )
